import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Moeiz",
      email: "moeiz@gmail.com",
      password: bcrypt.hashSync("123"),
      isAdmin: true,
    },
    {
      name: "Ahad",
      email: "ahad@gmail.com",
      password: bcrypt.hashSync("000"),
      isAdmin: false,
    },
  ],
  tileDisplay: [
    {
      _id: 1,
      image: "/images/tileDisplay/joint-pain.jpg",
    },
  ],
  sliderItems: [
    {
      _id: 1,
      image: "/images/slider/1.jpg",
    },
    {
      _id: 2,
      image: "/images/slider/2.jpg",
    },
    {
      _id: 3,
      image: "/images/slider/3.jpg",
    },
  ],
  category: [
    {
      title: "Medicines",
      image: "/images/category/medicines.jpg",
    },
    {
      title: "Personal Care",
      image: "/images/category/personal.jpg",
    },
    {
      title: "Lifestyle",
      image: "/images/category/lifestyle.jpg",
    },
    {
      title: "Organic",
      image: "/images/category/organic.jpg",
    },
    {
      title: "Health Care",
      image: "/images/category/health.jpg",
    },
    {
      title: "Carebaby",
      image: "/images/category/babycare.jpg",
    },
  ],
  products: [
    {
      title: "Brufen DS 90ml",
      slug: "brufen-ds-90ml",
      desc: "Brufen DS 90ml Syrup is used to treat the symptoms of pain in conditions like osteoarthritis, joint pain, shoulder pain, and inflammation. It contains Ibuprofen as an active ingredient and belongs to the non-steroidal anti-inflammatory class of drugs",
      category: "Medicines",
      image: "/images/products/Brufen-DS-90ml.jpg",
      brand: "Abbott Laboratories",
      countInStock: 0,
      price: "80.00",
    },
    {
      title: "Calpol 500mg",
      slug: "calpol-500mg",
      desc: "Calpol 500mg Tablet is used to treat pain and fever. It can be used alone or in combination. Calpol 500mg Tablet contains paracetamol as an active ingredient and belongs to the antipyretic and analgesic class of drugs.",
      category: "Medicines",
      image: "/images/products/Calpol-500mg.jpg",
      brand: "Glaxo Smith Kline",
      countInStock: 5,
      price: "374.00",
    },
    {
      title: "Panadol 500mg",
      slug: "panadol-500mg",
      desc: "Panadol 500mg Tablet is helpful for the treatment of migraine, headache, toothache, backache, sore throat, and helps to reduce the temperature. Each tablet of Panadol 500mg contains Paracetamol 500mg as an active ingredient.",
      category: "Medicines",
      image: "/images/products/Panadol-500mg.jpg",
      brand: "Glaxo Smith Kline",
      countInStock: 10,
      price: "470.00",
    },
    {
      title: "Panadol Extra 100",
      slug: "panadol-extra-100",
      desc: "Panadol Extra 100 Tablet is used to treat the symptoms of Fever, headache, earache, Muscle pain Migraine Osteoarthritis, Sore throat, and toothache.",
      category: "Medicines",
      image: "/images/products/Panadol-Extra-100.jpg",
      brand: "Glaxo Smith Kline",
      countInStock: 4,
      price: "275.00",
    },
    {
      title: "Stir-Up 10mg",
      slug: "stir-up-10mg",
      desc: "DStir Up 10mg Tablet is used for the treatment of dementia (severe confusion) related to Alzheimer's disease. Stir Up 10mg is also used to improve awareness, memory, and ability to perform daily functions.",
      category: "Medicines",
      image: "/images/products/Stir-Up-10mg.jpg",
      brand: "Nabiqasim Industries",
      countInStock: 11,
      price: "817.00",
    },
    {
      title: "Demantin 10mg",
      slug: "demantin-10mg",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Medicines",
      image: "/images/products/Demantin-10mg.jpg",
      brand: "Other",
      countInStock: 12,
      price: "1400.00",
    },
    {
      title: "Gouric 80mg",
      slug: "gouric-80mg",
      desc: "Gouric 80mg Tablet is used for the treatment of hyperuricemia (high uric acid levels) in patients with gout.",
      category: "Medicines",
      image: "/images/products/Gouric-80mg.jpg",
      brand: "Pharmevo (Private)",
      countInStock: 15,
      price: "805.00",
    },
    {
      title: "Hiloric 40mg",
      slug: "hiloric-40mg",
      desc: "Hiloric 40mg Tablet is used for the treatment of issues caused by an increase in uric acid levels. It is helpful for arthritis, and gout. Hiloric 40mg Tablet helps by decreasing the symptoms of gout like swelling, pain, and soreness. It is good against the symptoms like stiffness, too.",
      category: "Medicines",
      image: "/images/products/Hiloric-40mg.jpg",
      brand: "Highnoon Laboratories",
      countInStock: 15,
      price: "320.00",
    },
    {
      title: "Spiano 100mg",
      slug: "spiano-100mg",
      desc: "Spiano 100mg Tablet helps treat swelling, redness (inflammation) and pain. It contains Aceclofenac and belongs to a class of drugs known as non-steroidal anti-inflammatory drugs (NSAIDs). They usually have anti-inflammatory and painkiller properties. Spiano 100mg Tablet helps control the pain by lowering swelling and redness.",
      category: "Medicines",
      image: "/images/products/Spiano-100mg.jpg",
      brand: "Continental Pharmaceutical Ind Co",
      countInStock: 15,
      price: "282.00",
    },
    {
      title: "Urigo 40mg",
      slug: "urigo-40mg",
      desc: "Urigo 40mg Tablet is used to control, prevent, and treat increased pain symptoms and swelling in gout patients. Urigo works by lowering the amount of uric acid production in the body. It prevents the re-occurrence of gout attacks.",
      category: "Medicines",
      image: "/images/products/Urigo-40mg.jpg",
      brand: "Sami Pharm",
      countInStock: 15,
      price: "320.00",
    },
    {
      title: "Urigo 80mg",
      slug: "urigo-80mg",
      desc: "Urigo 80mgTablet is used to treat the symptoms of gout and high uric acid levels. It is recommended to people who cannot take allopurinol.",
      category: "Medicines",
      image: "/images/products/Urigo-80mg.jpg",
      brand: "Sami Pharm",
      countInStock: 15,
      price: "400.00",
    },
    {
      title: "Stablon",
      slug: "stablon",
      desc: "Stablon Tablet is helpful for the treatment of depression.  It is an atypical antidepressant and helps to brighten up the mood. Stablon Tablet is considered useful in treating depression that is unresponsive to alternative treatment.",
      category: "Medicines",
      image: "/images/products/Stablon.jpg",
      brand: "Servier Pharma",
      countInStock: 15,
      price: "437.00",
    },
    {
      title: "Blackmores Executive Formula",
      slug: "blackmores-executive-b-stress-formula",
      desc: "Blackmores Executive B Stress Formula Tablet helps treat nervous system functions. It provides sufficient energy to sustain good health and wellbeing. It contains vitamins and minerals and belongs to a class of drugs known as Multivitamins.",
      category: "Medicines",
      image: "/images/products/Blackmores-Executive-B-Stress-Formula.jpg",
      brand: "Blackmores",
      countInStock: 15,
      price: "1690.00",
    },
    {
      title: "Zauxit 20mg",
      slug: "zauxit 20mg",
      desc: "Zauxit 20mg Capsule is used for the treatment of mental or mood disorders such as; panic disorder, depression, eating disorder (bulimia), obsessive-compulsive disorder, premenstrual dysphoric disorder (premenstrual syndrome).",
      category: "Medicines",
      image: "/images/products/Zauxit-20mg.jpg",
      brand: "Zafa Pharmaceuticals Laboratories",
      countInStock: 15,
      price: "94.00",
    },
    {
      title: "Amorin 50mg",
      slug: "amorin-50mg",
      desc: "Amorin 50mg Tablet is helpful for the treatment of rheumatoid arthritis and Crohn's disease. Its active ingredient is Azathioprine and belongs to a class of drugs known as an immunosuppressant. It is useful for patients having kidney problems. It helps in facilitating the survival of organ transplant after surgeries.",
      category: "Medicines",
      image: "/images/products/Amorin-50mg.jpg",
      brand: "Mass Pharma",
      countInStock: 15,
      price: "1246.00",
    },

    //Personal Care

    {
      title: "Clean & Clear 50ml",
      slug: "clean-&-clear-50ml",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Clean-&-Clear-50ml.jpg",
      brand: "Generic",
      countInStock: 15,
      price: "210.00",
    },
    {
      title: "CreamyWash",
      slug: "creamywash",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/CreamyWash.jpg",
      brand: "Atco Laboratories",
      countInStock: 15,
      price: "559.00",
    },
    {
      title: "Depilus 15g",
      slug: "depilus-15g",
      desc: "Depilus 15g Cream is used to slow down the growth of unwanted hair on the face and under the chin in women.",
      category: "Personal Care",
      image: "/images/products/Depilus-15g.jpg",
      brand: "Atco Laboratories",
      countInStock: 15,
      price: "1250.00",
    },
    {
      title: "Fair & pink Gold Cream",
      slug: "fair-&-pink-gold-cream",
      desc: "Fair & Pink Cream is helpful for the treatment of dull and dark skin, brown spots, melasma, hyperpigmentation caused by the concentration of melanin. It gives a radiant and fair appearance, improves skin texture, and makes it soft. It uses Citric Acid and Ionized water as its natural components to make the skin whitening process natural. It includes Vitamins A, B, B3, and E, nourish and rejuvenate your skin to render a healthy look to your personality.",
      category: "Personal Care",
      image: "/images/products/Fair-&-pink-Gold-Cream.jpg",
      brand: "Pharma Health Pakistan",
      countInStock: 15,
      price: "3500.00",
    },
    {
      title: "U Veil Forte 60g",
      slug: "u-veil-forte-60g",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/U-Veil-Forte-60g.jpg",
      brand: "Other",
      countInStock: 15,
      price: "375.00",
    },
    {
      title: "NB Aloe Vera Gel 5000mg",
      slug: "nb-aloe-vera-gel-5000mg",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/NB-Aloe-Vera-Gel-5000mg.jpg",
      brand: "Nature's Bounty",
      countInStock: 15,
      price: "723.00",
    },
    {
      title: "Acnol Liq Cleanser 100ml",
      slug: "acnol-liq-cleanser-100ml",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Acnol-Liq-Cleanser-100ml.jpg",
      brand: "Other",
      countInStock: 15,
      price: "250.00",
    },
    {
      title: "Garnier Pure Active 3-in-1",
      slug: "garnier-pure-active-3-in-1",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Garnier-Pure-Active-3-in-1.jpg",
      brand: "Loreal Paris",
      countInStock: 15,
      price: "350.00",
    },
    {
      title: "Always Maxi Thick Extra",
      slug: "always-maxi-thick-extra-long-8-pcs",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Always-Maxi-Thick-Extra-Long-8-Pcs.jpg",
      brand: "Procter & Gamble",
      countInStock: 15,
      price: "328.00",
    },
    {
      title: "Veet Normal 25ml",
      slug: "veet-normal-25ml",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Veet-Normal-25ml.jpg",
      brand: "Reckitt Benckiser Pak",
      countInStock: 15,
      price: "125.00",
    },
    {
      title: "Fast Sign Plus",
      slug: "fast-sign-plus",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Fast-Sign-Plus.jpg",
      brand: "Other",
      countInStock: 15,
      price: "1000.00",
    },
    {
      title: "Always Ultra Large 8 Pcs",
      slug: "always-ultra-large-8-pcs",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Always-Ultra-Large-8-Pcs.jpg",
      brand: "Procter & Gamble",
      countInStock: 15,
      price: "177.00",
    },
    {
      title: "Minoxin 2 % (60ml)",
      slug: "minoxin-2-%-(60ml)",
      desc: "Minoxin 2% 60ml Solution is used to help hair growth during the treatment of male pattern baldness. Minoxin 2% is also used to help hair growth in females with thinning hair.",
      category: "Personal Care",
      image: "/images/products/minoxin.jpg",
      brand: "Brookes Pharmaceutical Labs",
      countInStock: 15,
      price: "550.00",
    },
    {
      title: "Biolyn Anti Hairfall Shampoo",
      slug: "biolyn-anti-hairfall-shampoo",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Biolyn-Anti-Hairfall-Shampoo.jpg",
      brand: "Other",
      countInStock: 15,
      price: "1380.00",
    },
    {
      title: "Dettol Sanitizer 50ml",
      slug: "dettol-sanitizer-50ml",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Personal Care",
      image: "/images/products/Dettol-Sanitizer-50ml.jpg",
      brand: "Reckitt Benckiser",
      countInStock: 15,
      price: "260.00",
    },

    //Lifestyle

    {
      title: "Lacta-D",
      slug: "lacta-d",
      desc: "Nutrifactor Lacta D Tablet is used to improve calcium absorption and utilization into the bones. Nutrifactor Lacta D is also used to maintain the normal functioning of the nervous and immune systems. Nutrifactor Lacta D is also used to reduce the risks of fractures, rickets, tooth loss, and osteomalacia.",
      category: "Lifestyle",
      image: "/images/products/Lacta-D.jpg",
      brand: "Nutrifactor Natural Supplement",
      countInStock: 15,
      price: "590.00",
    },
    {
      title: "Tanakan",
      slug: "tanakan",
      desc: "Tanakan Tablet is helpful for the treatment of minor, age-related neurological, and cognitive problems. It contains ginkgo biloba extractum normatum (EG 761) as an active ingredient. It contains a plant extract that aims to facilitate blood circulation.",
      category: "Lifestyle",
      image: "/images/products/Tanakan.jpg",
      brand: "Atco Laboratories",
      countInStock: 15,
      price: "444.00",
    },
    {
      title: "Cogniza 120ml",
      slug: "cogniza-120ml",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Cogniza-120ml.jpg",
      brand: "Highnoon Laboratories",
      countInStock: 15,
      price: "246.00",
    },
    {
      title: "Pregnazon",
      slug: "pregnazon",
      desc: "Pregnazon Capsule is helpful for the treatment of mineral deficiency, brain, and eye disorders. It contains high folic acid, iron, vitamin B12, zinc, and other essential nutrients including omega-3 that is rich in EPA/DHA, crucial for the development of a baby’s brain and nervous system.",
      category: "Lifestyle",
      image: "/images/products/Pregnazon.jpg",
      brand: "Health Aid Pharma",
      countInStock: 15,
      price: "1250.00",
    },
    {
      title: "Durex Extra Safe",
      slug: "durex-extra-safe",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Durex-Extra-Safe.jpg",
      brand: "Durex",
      countInStock: 15,
      price: "270.00",
    },
    {
      title: "Durex Performa",
      slug: "durex-performa",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Durex-Performa.jpg",
      brand: "Durex",
      countInStock: 15,
      price: "265.00",
    },
    {
      title: "Durex Play Tingler",
      slug: "Durex-Play-Tingler",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Durex-Play-Tingler.jpg",
      brand: "Durex",
      countInStock: 15,
      price: "630.00",
    },
    {
      title: "Klimax Condoms",
      slug: "klimax-condoms",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Klimax-Condoms.jpg",
      brand: "KAREX Industries",
      countInStock: 15,
      price: "200.00",
    },
    {
      title: "One Touch Classic Condoms",
      slug: "one-touch-classic-condoms",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/One-Touch-Classic-Condoms.jpg",
      brand: "Forans Medical",
      countInStock: 15,
      price: "200.00",
    },
    {
      title: "NF Skin Hair Nails Formula",
      slug: "NF-Skin-Hair-Nails-Formula",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/NF-Skin-Hair-Nails-Formula.jpg",
      brand: "Nutrifactor Natural Supplement",
      countInStock: 15,
      price: "950.00",
    },
    {
      title: "Kidz Vits Gummies",
      slug: "kidz-vits-gummies",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Kidz-Vits-Gummies.jpg",
      brand: "Ccl",
      countInStock: 15,
      price: "700.00",
    },
    {
      title: "Dermaxil Ultra",
      slug: "dermaxil-ultra",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Dermaxil-Ultra.jpg",
      brand: "Other",
      countInStock: 15,
      price: "799.00",
    },
    {
      title: "NF Extra C",
      slug: "nf-extra-c",
      desc: "Nutrifactor Extra-C Tablet is used to boost the immune system and treat symptoms of the common cold. Nutrifactor Extra-C is also to relieve the symptom of the respiratory tract such as runny nose, sneezing, and congestion. Nutrifactor Extra-C is also used to repair and maintain bones, cartilage, and teeth. Nutrifactor Extra-C is also used for the treatment of bleeding gums, weak immune systems, skin weakness, and scurvy anemia.",
      category: "Lifestyle",
      image: "/images/products/NF-Extra-C.jpg",
      brand: "Nutrifactor Natural Supplement",
      countInStock: 15,
      price: "1442.00",
    },
    {
      title: "Imune 120ml",
      slug: "imune-120ml",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Imune-120ml.jpg",
      brand: "Himont Pharmaceutical",
      countInStock: 15,
      price: "383.00",
    },
    {
      title: "Nature's Bounty B12 500mcg",
      slug: "nature's-bounty-b12-500mcg",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Lifestyle",
      image: "/images/products/Nature's-Bounty-B12-500mcg.jpg",
      brand: "Nature's Bounty",
      countInStock: 15,
      price: "2821.00",
    },

    //Organic

    {
      title: "Qarshi Toot Siah 120ml syrup",
      slug: "Qarshi-Toot-Siah-120ml-syrup",
      desc: "Qarshi Toot Siah is a herbal formula syrup made up of black mulberry extract. It is indicated for various throat infections like pharyngitis, hoarseness (raspy voice), and a painful throat. It contains not only the extract but also the fruit pulp, making it the greatest natural therapy for sore throat and other associated problems. Thick black mulberry syrup relieves sore throat pain and agitation by reducing inflammation in the throat, inducing relaxing effects, and reducing pain and agitation. Cough is one of the conditions for which it is prescribed. It can be used to treat coughs that are dry, unpleasant, or uncomfortable. It reduces lung inflammation and relieves bronchitis.",
      category: "Organic",
      image: "/images/products/Qarshi-Toot-Siah-120ml-syrup.jpg",
      brand: "Qarshi",
      countInStock: 15,
      price: "90.00",
    },
    {
      title: "Safi Syrup syrup",
      slug: "safi-syrup-syrup",
      desc: "Hamdard Safi syrup is used for clearing the skin and purifying the blood, which ultimately makes your skin appear radiant, glowing, and healthy. Apart from being used as a blood purifier, it helps treat zits, pimples, acne, and unwanted sun spots. It also prevents constipation, dyspepsia, and nose bleeds. With the Safi syrup, you can treat skin issues like rashes, boils, and hives.",
      category: "Organic",
      image: "/images/products/Safi-Syrup-syrup.jpg",
      brand: "Hamdard",
      countInStock: 15,
      price: "90.00",
    },
    {
      title: "Iberogast Solution",
      slug: "iberogast-solution-50ml-solution",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Organic",
      image: "/images/products/Iberogast-Solution-50ml-solution.jpg",
      brand: "Bayer",
      countInStock: 15,
      price: "592.00",
    },
    {
      title: "Surfi 250s tablet",
      slug: "surfi-250s-tablet",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Organic",
      image: "/images/products/Surfi-250s-tablet.jpg",
      brand: "Qarshi",
      countInStock: 15,
      price: "247.00",
    },
    {
      title: "R-96 Sinusitis spray",
      slug: "r-96-sinusitis-spray",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Organic",
      image: "/images/products/R-96-Sinusitis-spray.jpg",
      brand: "Dr. Reckeweg",
      countInStock: 15,
      price: "1053.00",
    },
    {
      title: "R 94 Cicatin Calendula Lotion",
      slug: "r-94-cicatin-calendula-lotion",
      desc: "Dr. Reckeweg R-94 lotion is a homeopathic remedy for wounds, minor cuts and burns. It is used to saturate a bandage. It promotes wound healing. Calendula in this lotion is highly effective for lacerated wounds and bruises. It not only aids in wound healing but it also prevents infections of the wound and reduces inflammation.",
      category: "Organic",
      image: "/images/products/R-94-Cicatin-Calendula-Lotion.jpg",
      brand: "Dr. Reckeweg",
      countInStock: 15,
      price: "873.00",
    },
    {
      title: "Mullein Oil Ear Drop",
      slug: "mullein-oil-ear-drop",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Organic",
      image: "/images/products/Mullein-Oil-Ear-Drop.jpg",
      brand: "Dr. Reckeweg",
      countInStock: 15,
      price: "855.00",
    },
    {
      title: "Gestofill 120ml Syrup",
      slug: "gestofill-120ml-syrup",
      desc: "Gestofill syrup is a complete herbal remedy for treating flatulence (built up of gas) and indigestion. It eases symptoms of heartburn by stimulating digestion. Its carminative properties increase peristalsis (involuntary movement of the digestive tract) which relieves abdominal pain, cramping and distension (accumulation of fluid or gas in abdomen).",
      category: "Organic",
      image: "/images/products/Gestofill-120ml-Syrup.jpg",
      brand: "New",
      countInStock: 15,
      price: "99.00",
    },
    {
      title: "Herbion Ispaghol Orange Jar",
      slug: "herbion-ispaghol-orange-jar",
      desc: "Herbion ispaghol is a natural dietary supplement. It is extracted from natural ispaghol seeds. Ispaghol is a rich source of fiber. It is also used as a supportive therapy in reducing constipation and blood cholesterol. Husk increases water absorption during digestion which allows the stool to soften and makes defecation easier. It regulates the consistency and frequency of stools in people with improper digestion and relieves flatulence and bloating. Apart from treating constipation it also reduces cholesterol and the risk of high cholesterol associated diseases. Ispaghol effectively reduces weight by improving lipid and sugar levels in the blood.",
      category: "Organic",
      image: "/images/products/Herbion-Ispaghol-Orange-Jar.jpg",
      brand: "Herbion",
      countInStock: 15,
      price: "720.00",
    },
    {
      title: "Qarshi Jam-e-Shirin 800ml",
      slug: "qarshi-jam-e-shirin-800ml-liquid",
      desc: "Qarshi jam-e-shirin is a refreshing and pleasant tasting syrup which is made up of natural herb extracts. It is a multipurpose syrup that can be used as a drink when mixed with water or milk or as a topping on various desserts such as ice cream and cakes. Because of its natural distillates its taste never changes and lasts long.",
      category: "Organic",
      image: "/images/products/Qarshi-Jam-e-Shirin-800ml-Liquid.jpg",
      brand: "Qarshi",
      countInStock: 15,
      price: "252.00",
    },
    {
      title: "Jawarish Amla Sada 100 Gram",
      slug: "jawarish-amla-sada-100-gram-powder",
      desc: "Hamdard jawarish amla sada is a herbal medicine enriched with the goodness of vitamin C. It increases immunity and strengthens the heart and brain. It regulates functions of liver and stomach, maintains gastrointestinal health. It is proven to be effective in treating diarrhea and dysentery (diarrhea with blood), and lowers abnormal gastric and hepatic heat. Jawarish amla sada is also known to anti-tachy cardiac as it lowers fast heart beat.",
      category: "Organic",
      image: "/images/products/Jawarish-Amla-Sada-100-Gram-Powder.jpg",
      brand: "Hamdard",
      countInStock: 15,
      price: "72.00",
    },
    {
      title: "Hamdard Jawarish Jalinoos",
      slug: "hamdard-jawarish-jalinoos-100gram",
      desc: "Hamdard jawarish jalinoos is a herbal medicine that caters to the problems of the digestive system. It is effective in improving the function of the digestive system. It relieves abdominal distension, flatulence, hyperacidity, and feeling of heaviness after meals. It improves the intestinal function and prevents constipation. Jawarish jalinoos also reduces the frequency of urination, treats piles and aids in dissolving the stones in gallbladder or kidney. Its continuous use prevents the lightning of hair colour.",
      category: "Organic",
      image: "/images/products/Hamdard-Jawarish-Jalinoos-100gram.jpg",
      brand: "Hamdard",
      countInStock: 15,
      price: "288.00",
    },
    {
      title: "Hamdard Jernide 120ml Liquid",
      slug: "hamdard-jernide-120ml-liquid",
      desc: "Jernide formulation is an herbal medicine indicated for relieving male reproductive organ hypersensitivity (undesirable reactions). Excessive spermatorrhoea (excessive involuntary semen discharge) and wet dreams are caused by inflammation, which irritates the sexual organs and makes them hypersensitive. The hypersensitivity of the genital organs promotes seminal discharge (ejaculate fluid containing sperm in it), which leads to the weakening of muscles and nerves. Such night emissions should not be ignored and should be handled as soon as possible, since they can lead to premature ejaculation (sexual dysfunction) or impotency (unable to achieve erection) over time. Jernide helps relieve this hypersensitivity as well as swelling of seminiferous tubules (tubules found within testes) in a very effective way. It aids in the correction of its functioning, reducing micturition (urination), burning & preventing seminal discharge. It prevents nocturnal (nightly) emission, spermatorrhea, and premature ejaculation. It contains Glycyrrhiza glabra (reduces seminal discharge and eliminates the feeling of burning while urinating), Cascara sagrada extract (relaxation of neighboring male sexual organs and reduction in nocturnal emission & spermatorrhea), and Atropa acuminata extract (relieve testicular pain and inflammation).",
      category: "Organic",
      image: "/images/products/Hamdard-Jernide-120ml-Liquid.jpg",
      brand: "Hamdard",
      countInStock: 15,
      price: "144.00",
    },
    {
      title: "Hamdard Hiknol 25 Gram",
      slug: "hamdard-hiknol-25-gram",
      desc: "Hamdard Hiknol is a herbal ointment. It is a topical treatment, because of its antibacterial, antipruritic, antiseptic nature it treats various skin lesions. It prevents sepsis of wounds and eliminates pus. It is safe to use and does not cause any harm to the skin.",
      category: "Organic",
      image: "/images/products/Hamdard-Hiknol-25-Gram.jpg",
      brand: "Hamdard",
      countInStock: 15,
      price: "108.00",
    },
    {
      title: "Hamdard Khuban 175ml Liquid",
      slug: "hamdard-khuban-175ml-liquid",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Organic",
      image: "/images/products/Hamdard-Khuban-175ml-Liquid.jpg",
      brand: "Hamdard",
      countInStock: 15,
      price: "135.00",
    },

    //HealthCare

    {
      title: "Omron NE-C803-E Nebulizer",
      slug: "omron-nebulizer-ne-c803-e-nebulizer",
      desc: "Omron compressor nebulizer is the best solution for those who need a basic version of it. It treats patients with lower respiratory tract infections in the most hygienic and effective way. The small and handy design makes it easy to carry and use whenever it is needed. It appropriately delivers the correct amount of drug into the respiratory tract and relieves the congestion and obstructions. Unlike most of the nebulizers, it is the quietest of all and ensures that the drug delivery is comfortable.",
      category: "Health Care",
      image: "/images/products/Omron-Nebulizer-NE-C803-E-Nebulizer.jpg",
      brand: "Omron",
      countInStock: 15,
      price: "6750.00",
    },
    {
      title: "Revolizer Device",
      slug: "revolizer-device",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Health Care",
      image: "/images/products/Revolizer-Device.jpg",
      brand: "Highnoon",
      countInStock: 15,
      price: "590.00",
    },
    {
      title: "BD Syringe 5ml Syringe",
      slug: "bd-syringe-5ml-syringe",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Health Care",
      image: "/images/products/BD-Syringe-5ml-Syringe.jpg",
      brand: "New",
      countInStock: 15,
      price: "36.00",
    },
    {
      title: "Accu-Chek Performa 50' Strips",
      slug: "accu-chek-performa-50'-strips-glucose-monitor-strips",
      desc: "-To determine blood glucose levels. Help to measure the glucose easily. Convenient and easy to use. Quick and accurate blood testing",
      category: "Health Care",
      image:
        "/images/products/Accu-Chek-Performa-50'-Strips-Glucose-Monitor-Strips.jpg",
      brand: "Roche",
      countInStock: 15,
      price: "1237.00",
    },
    {
      title: "Smart Flamingo Abdominal Belt",
      slug: "smart-flamingo-abdominal-belt-2002-small-bandage",
      desc: "This abdominal belt works its magic to compress and support your abdominal muscles and gives you amazing and notable results with regard to waistline reduction. The belt is also used to protect and bind surgical; incisions of the abdomen. Made from breathable and high-quality fabric, it ensures good ventilation and comfort.",
      category: "Health Care",
      image:
        "/images/products/Smart-Flamingo-Abdominal-Belt-2002-Small-Bandage.jpg",
      brand: "Smart Flamingo",
      countInStock: 15,
      price: "2925.00",
    },
    {
      title: "Smart-Flamingo-Rib-Belt-Small",
      slug: "Smart-Flamingo-Rib-(Chest)-Belt-2028-Small",
      desc: "This belt is used to hold the thoracic, upper abdominal region and rib cage to fix fracture or even pulled muscles. Wearing this belt facilitates you in breathing and when you do deep breathing exercise. This is an ideal product for stabilization of sternum fractures. This belt can be used for post-operative care or a rib-cage fracture. It is light-weight and thin and doesn't look odd on clothes. Moreover, the rib belt is flexible and allows comfortable breathing.",
      category: "Health Care",
      image: "/images/products/Smart-Flamingo-Rib-(Chest)-Belt-2028-Small.jpg",
      brand: "Smart Flamingo",
      countInStock: 15,
      price: "3600.00",
    },
    {
      title: "Smart Flamingo Spoon Splint",
      slug: "smart-flamingo-spoon-splint-2101-small",
      desc: "This Smart Flamingo Spoon Splint is recommended to be used for support and protection of dislocated fractures. Its upward curve at the tip provides protection to end of the finger. Get great relief quickly by wearing this splint spoon.",
      category: "Health Care",
      image: "/images/products/Smart-Flamingo-Spoon-Splint-2101-Small.jpg",
      brand: "Smart Flamingo",
      countInStock: 15,
      price: "945.00",
    },
    {
      title: "Freestyle Glucometer Strips",
      slug: "freestyle-glucometer-strips-'50s'-glucose-monitor-strips",
      desc: "Keeping a record with convenience and accuracy! FreeStyle Optium Glucose Test Strips are available for self-testing of blood glucose and can be used with FreeStyle Optium Neo, FreeStyle Optium, Optium Xceed, Optium and TrueSense Meters.These strips show increased accuracy with fewer errors with enhanced features of foil wrapping to enhance protection from air and moisture. Visual confirmation feature makes it easy for the customer to assure blood sample has been drawn.",
      category: "Health Care",
      image:
        "/images/products/Freestyle-Glucometer-Strips-'50s'-Glucose-Monitor-Strips.jpg",
      brand: "FreeStyle",
      countInStock: 15,
      price: "1435.00",
    },
    {
      title: "Certeza Aneroid CR-1002",
      slug: "certeza-aneroid-sphygmomanometer-(standard-size)-CR-1002",
      desc: "Live a healthier life by breathing fresh and clean air.",
      category: "Health Care",
      image:
        "/images/products/Certeza-Aneroid-Sphygmomanometer-(Standard-Size)-CR-1002.jpg",
      brand: "Certeza",
      countInStock: 15,
      price: "1900.00",
    },
    {
      title: "Certeza CR 2001",
      slug: "certeza-mercurial-free-sphygmomanometer-(desk-type)-cr-2001",
      desc: "The sphygmomanometer is a device used to measure blood pressure. This set combines the accurate traditional mercurial instrument with mobility, durability and added reliability. Also includes Graduated glass tube, Nylon Standard Size Cuff and Latex Bladder.",
      category: "Health Care",
      image:
        "/images/products/Certeza-Mercurial-Free-Sphygmomanometer-(Desk-Type)-CR-2001.jpg",
      brand: "Certeza",
      countInStock: 15,
      price: "9310.00",
    },
    {
      title: "Beurer Blood Pressure ",
      slug: "beurer-cuff-type-blood-pressure-monitor-bm-58",
      desc: "Beurer Cuff Type Blood Pressure Monitor BM-58 is fully-automatic and takes blood pressure measurement on the upper arm. The display is perfect to read with white illuminated XL display (70 x 82 mm). Start/stop button is illuminated with sensor-touch buttons. Average of all saved measured values and morning and evening blood pressure for the last 7 days is displayed with 2 x 60 memory spaces. There is optimal control of the upper arm with circumferences 22 - 36 cm. The automatic switch-off function is provided with automatic pressure pre-selection and deflation. Storage pouch included. This easy-to-use has Bluetooth 4.0 wireless technology for transmission of the measured values to your Smartphone.",
      category: "Health Care",
      image:
        "/images/products/Beurer-Cuff-Type-Blood-Pressure-Monitor-Bm-58.jpg",
      brand: "Beurer",
      countInStock: 15,
      price: "12350.00",
    },
    {
      title: "SHARP Air Purifier",
      slug: "sharp-air-purifier-with-plasmaCluster-and-hepa-filter-(fu-j30sa-b)",
      desc: "Live a healthier life by breathing fresh and clean air. Sharp plasmacluster air purifier makes the environment of your home, office or any other setting fresher, healthier and cleaner. This air purifier by Sharp combines patented Plasmacluster ion technology with True HEPA filtration to clean the environment in which you breathe. Patented plasmacluster ion releasing from this air purifier reduces bacteria viruses, mold and fungus. The air purifiers by Sharp are tested by independent laboratories to verify the air-cleaning capability of the filtration system.",
      category: "Health Care",
      image:
        "/images/products/SHARP-Air-Purifier-With-PlasmaCluster-and-HEPA-Filter-(FU-J30SA-B).jpg",
      brand: "Sharp",
      countInStock: 15,
      price: "47700.00",
    },
    {
      title: "Dignity Sheets",
      slug: "dignity-sheet-(under-pad)-x-large-sheets",
      desc: "Dignity Sheets are disposable and water resistant sheets that are perfect for everyday usage and will keep your patient safe in any situation. The disposable dignity sheet is single-use and patient-specific, soaking up any water and leaving your patient feeling comfortable and dry. It is highly recommended and necessary for daily use in high-intensity workload regions where patient behavior is unpredictable since it protects the patient and provides immediate relief. The virgin fluff pulp, high-tech SAP, and absorbent tissue make up the bottom PE cast film, hot rolled non-woven fabric, and middle absorbent layer of the sheet. The large sheet comes in width of 600 mm, and the length of 900 mm. It is intended for cases like gynecological examination, hospital departments, bed ridden & elderly patients, menstrual periods, postpartum (after pregnancy), beauty care, baby bed sheet and hotels etc",
      category: "Health Care",
      image: "/images/products/Dignity-Sheet-(Under-Pad)-X-Large-Sheets.jpg",
      brand: "Healthcare Supplies",
      countInStock: 15,
      price: "670.00",
    },
    {
      title: "Accu-Check-Active-Strips-25s",
      slug: "accu-check-active-strips-25s-strip",
      desc: "Use these high-quality blood strips to measure your glucose. The Accu Check Blood Strips are designed to easily check the glucose, a type of sugar, in your blood. These strips are easy to handle and measure the amount of glucose. Also, the strips are compatible with the blood glucose meter.",
      category: "Health Care",
      image: "/images/products/Accu-Check-Active-Strips-25s-Strip.jpg",
      brand: "Roche",
      countInStock: 15,
      price: "855.00",
    },
    {
      title: "Medisign Pro Nebulizer (1 Set)",
      slug: "medisign-pro-nebulizer-(1-Set)",
      desc: "The Medisign Pro Nebulizer is a medicinal equipment ideal for the effective and efficient delivery of aerosol medications with great clinical accuracy. It is built with high-quality and durable components to offer users long-time usage. It delivers medicine in a mist form that is inhaled into the lungs. It is a powerful machine with a piston driven compressor and one-button start operation. Furthermore, it is latex free, easy to clean and carry, easy to store, and ideal for all ages. Nebulizers are used for several conditions, including asthma, cystic fibrosis, Chronic Obstructive Pulmonary Disease (COPD), and other respiratory disorders.",
      category: "Health Care",
      image: "/images/products/Medisign-Pro-Nebulizer-(1-Set).jpg",
      brand: "Medisign",
      countInStock: 15,
      price: "3800.00",
    },

    //Carebaby

    {
      title: "Enfamil A.R Powder",
      slug: "enfamil-a.r-powder-400g-powder",
      desc: "Enfamil A.R.  is suitable for infants from birth on when not breastfed. Enfamil A.R. is for the dietary management of regurgitation or spitting up and can be used as a sole source of nourishment up to 6 months of age and as the basis of diversified diet for older infants. Enfamil A.R.  is a nutritionally complete, pre-thickened formula containing a unique rice starch thickener that is thin in the bottle and thickens in the stomach",
      category: "Carebaby",
      image: "/images/products/Enfamil-A-R-Powder-400g-Powder.jpg",
      brand: "Mead Johnsons Nutrition",
      countInStock: 15,
      price: "3793.00",
    },
    {
      title: "Enfamil A+ 1 Powder",
      slug: "enfamil-a+1-400gm-milk-powder",
      desc: "Enfamil A+ formula is scientifically designed to fulfill all the nutritional requirements of an infant. It contains expert-recommended levels of DHA & ARA (fatty acids present in breast milk) that are most essential for cognitive development (how children think, explore, figure out things) during the early years of infancy. DHA not only helps in promoting healthy brain function but also aids in developing correct vision.  It is rich in essential nutrients like choline (for memory and learning), iron, calcium; magnesium, phosphorus, & vitamin D for strong teeth and bones; zinc (for brain cell growth), protein; copper, glucose, and riboflavin for energy to the brain cells. Enfamil A+ also contains prebiotics blend PDX & GOS that boost the growth of useful gut bacteria which eventually strengthen the immune system. It is manufactured by Mead Johnson Nutrition which is considered the world’s leading pediatric nutrition provider. It is easily digested by the infant and designed for feeding babies needing special care but don’t have special nutritional requirements.",
      category: "Carebaby",
      image: "/images/products/Enfamil-A+1-400gm-Milk-Powder.jpg",
      brand: "Mead Johnsons Nutrition",
      countInStock: 15,
      price: "2700.00",
    },
    {
      title: "Pediasure Chocolate Powder",
      slug: "pediasure-chocolate-400gm-milk-powder",
      desc: "An ideal nutritional supplement to ensure the proper growth and development of children aged 1-10 years. Featuring triple protein complex and the perfect  blend of advanced carbohydrates. Packed with vitamins, minerals, and nutrients, it is the complete nutritional package.",
      category: "Carebaby",
      image: "/images/products/Pediasure-Chocolate-400gm-Milk-Powder.jpg",
      brand: "Abbott Nutrition",
      countInStock: 15,
      price: "1545.00",
    },
    {
      title: "Pediasure Vanilla Powder",
      slug: "pediasure-vanilla-400gm-milk-powder",
      desc: "An ideal nutritional supplement to ensure the proper growth and development of children aged 1-10 years. Featuring triple protein complex and the perfect  blend of advanced carbohydrates. Packed with vitamins, minerals, and nutrients, it is the complete nutritional package.",
      category: "Carebaby",
      image: "/images/products/Pediasure-Vanilla-400gm-Milk-Powder.jpg",
      brand: "Abbott Nutrition",
      countInStock: 15,
      price: "1545.00",
    },
    {
      title: "Beurer Digital BY 76",
      slug: "beurer-digital-steam-sterilizer-by-76",
      desc: "Sterilize your baby's products with ease. This device uses hot steam and helps you sterilize your baby's products. This device is compliant with all feeding bottles.",
      category: "Carebaby",
      image: "/images/products/Beurer-Digital-Steam-Sterilizer-BY-76.jpg",
      brand: "Beurer",
      countInStock: 15,
      price: "10450.00",
    },
    {
      title: "Morinaga BF Powder",
      slug: "morinaga-bf-1-milk-powder",
      desc: "Morinaga BF-1 is an infant formula especially designed for the nutritional support of infants when breastfeeding is not enough or opted. It is an essential source of vitamins, minerals, and other nutrients necessary for supporting the normal growth and development of the infants. It also supports the development of the digestive and immune systems.",
      category: "Carebaby",
      image: "/images/products/Morinaga-BF-1-Milk-Powder.jpg",
      brand: "Morinaga",
      countInStock: 15,
      price: "3705.00",
    },
    {
      title: "Morinaga BF Powder",
      slug: "morinaga-bf-2-milk-powder",
      desc: "Morinaga BF-2 is a follow-up formula especially designed for children older than 6 months of age to complement the weaning diet or when breastfeeding is not an option. It is an essential source of vitamins, minerals, and other nutrients necessary for supporting the normal growth and development of the child. It prevents nutritional deficiencies and also supports the digestive and immune systems.",
      category: "Carebaby",
      image: "/images/products/Morinaga-BF-2-Milk-Powder.jpg",
      brand: "Morinaga",
      countInStock: 15,
      price: "3705.00",
    },
    {
      title: "Beurer Food Warmer - BY 52",
      slug: "beurer-digital-baby-food-warmer-by-52",
      desc: "This device keeps the food of your baby warm. It features a LED display that clearly displays the temperature at which the food is being warmed. As it is specifically designed for babies, the device ensures that the baby food is heated gently and evenly. Also, it is designed in such a way that it can conveniently hold all sorts of jars and bottles carrying baby food items. A lifter also comes with it so that you can remove the jars or bottles easily. This is surely a convenient way to give your baby warm and fresh food every time.",
      category: "Carebaby",
      image: "/images/products/Beurer-Digital-Baby-Food-Warmer-BY-52.jpg",
      brand: "Beurer",
      countInStock: 15,
      price: "7125.00",
    },
    {
      title: "Meiji Mamilac Milk Powder",
      slug: "meiji-mamilac-milk-powder",
      desc: "This nutritious sucrose free formula is formulated for pregnant and breastfeeding women. It contains DHA, that is essential for the development of eye and brain. Moreover, it has folic acid which prevents neural tube defects in infants. It further has iron and calcium, that increase blood volume and help in the formation of bones. Zinc is also present in it as it helps in the normal functioning of the reproductive system.",
      category: "Carebaby",
      image: "/images/products/Meiji-Mamilac-Milk-Powder.jpg",
      brand: "Meiji",
      countInStock: 15,
      price: "1392.00",
    },
    {
      title: "Nestle' LACTOGEN 600g",
      slug: "nestle'-lactogen-1-400g-milk-powder",
      desc: "Nestle Lactogen 1 is an infant formula to provide nutritional value when they cannot be breastfed due to medical or other reasons. It is a source of essential vitamins, minerals, and other nutrients that are important for the healthy growth of the baby. It supports the digestive system and decreases stomach discomfort. Fortified with DHA and ARA, it plays an essential role in the brain and visual development of the baby.",
      category: "Carebaby",
      image: "/images/products/Nestle'-LACTOGEN-1-400g-Milk-Powder.jpg",
      brand: "Nestle",
      countInStock: 15,
      price: "910.00",
    },
    {
      title: "Nestle' LACTOGEN 400g",
      slug: "nestle'-lactogen-2-400g-milk-powder",
      desc: "Nestle Lactogen 2 is a follow-up formula for infants older than 6 months that fulfils their nutritional requirements and complements the weaning diet. It is a source of essential vitamins, minerals, and other nutrients that are important for healthy growth of an infant. It supports the digestive system and decreases stomach discomfort. Fortified with DHA and ARA, it plays an essential role in the brain and visual development of an infant. ",
      category: "Carebaby",
      image: "/images/products/Nestle'-LACTOGEN-2-400g-Milk-Powder.jpg",
      brand: "Nestle",
      countInStock: 15,
      price: "910.00",
    },
    {
      title: "Nestle' LACTOGROW 200g",
      slug: "Nestle'-lactogrow-3-200g-milk-powder",
      desc: "Nestle Lactogrow 3 is a growing-up formula for children older than 1 year of age. It is uniquely formulated to meet the daily nutritional requirements of the children. It contains a well-balanced amount of vitamins and minerals that prevent the nutritional and developmental issues faced by children. It supports the rapid growth stage and aids in the overall progress from infancy to childhood. Fortified with DHA and ARA, it plays an essential role in the brain and visual development of the child.",
      category: "Carebaby",
      image: "/images/products/Nestle'-LACTOGROW-3-200g-Milk-Powder.jpg",
      brand: "Nestle",
      countInStock: 15,
      price: "475.00",
    },
    {
      title: "Morinaga-BF-Mama",
      slug: "morinaga-bf-mama-nut-sup-vanilla-milk-powder",
      desc: "Morinaga BF-Mama is used for proper and sufficient nutritional support during pregnancy and lactation for the mother's own health and proper growth of the pre-born and suckling child.",
      category: "Carebaby",
      image:
        "/images/products/Morinaga-BF-Mama-Nut-Sup-Vanilla-Milk-Powder.jpg",
      brand: "Morinaga",
      countInStock: 15,
      price: "724.00",
    },
    {
      title: "Nestle Cerelac Wheat 350gm",
      slug: "nestle-cerelac-wheat-350gm-milk-powder",
      desc: "Nestle cerelac wheat is fortified with probiotics, vitamins, and minerals which support a baby’s growth and development. Nestle cerelac is carefully formulated to fulfil the needs of a growing baby. Nestle cerelac ensures easy digestibility and has naturally active probiotics that strengthen a baby’s natural defenses. Nestle cerelac wheat has a gentle taste and texture. Nestle cerelac wheat protects babies from developing nutritional deficiencies during their growing age.",
      category: "Carebaby",
      image: "/images/products/Nestle-Cerelac-Wheat-350gm-Milk-Powder.jpg",
      brand: "Nestle",
      countInStock: 15,
      price: "560.00",
    },
    {
      title: "Nestle Cerelac Fruits 350gm",
      slug: "nestle-cerelac-3-fruits-350gm-milk-powder",
      desc: "Nestle cerelac 3 fruits is specially designed to fulfil the nutritional needs of a growing baby. This cerelac supports the physical and cognitive development of a baby, boosts immunity, fulfils a baby’s daily need of iron, and makes the transition to solid food easier. Nestle cerelac 3 fruits assists in developing a strong and sturdy physique and keeps a baby’s tummy full for a longer time period.",
      category: "Carebaby",
      image: "/images/products/Nestle-Cerelac-3-Fruits-350gm-Milk-Powder.jpg",
      brand: "Nestle",
      countInStock: 15,
      price: "560.00",
    },
  ],
};

export default data;
